name: Auto-Scraping Proprietà

on:
  schedule:
    - cron: '0 */4 * * *'  # Ogni 4 ore
  workflow_dispatch:  # Manuale

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml
      
      - name: Run scraper
        run: python scraper.py
      
      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add properties.json
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update: Nuove proprietà immobiliari ($(date))"
            git push
          else
            echo "Nessuna nuova proprietà da aggiungere"
          fi